---

# Role execution order

- hosts: 127.0.0.1
  roles:
    - { role: users, tags: users }
    - { role: system, tags: system }
    - { role: sysctl, tags: sysctl }
    - { role: wireguard-pf, tags: wireguard-pf }}
    - { role: wireguard-pkg, tags: wireguard-pkg }
    - { role: wireguard-configs, tags: wireguard
    - { role: reboot, tags: reboot }
